if(UNIX AND NOT APPLE)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(GTKMM REQUIRED gtkmm-4.0)
    include_directories(${GTKMM_INCLUDE_DIRS})
elseif(APPLE)
    message(STATUS "macOS")
    list(APPEND LIBS -framework Cocoa -framework IOKit -framework CoreVideo)
    list(APPEND LIBS -L/usr/local/lib -L/opt/local/lib -L/opt/homebrew/lib)
    include_directories(/usr/local/include /opt/local/include /opt/homebrew/include)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(GTKMM REQUIRED gtkmm-4.0)
    list(APPEND LIBS ${GTKMM_LIBRARIES})
elseif(WIN32)
    message(STATUS "Windows (MinGW or MSVC)")
    find_package(PkgConfig REQUIRED)
    set(ENV{PKG_CONFIG_PATH} "C:/msys64/mingw64/lib/pkgconfig")
    pkg_check_modules(GTKMM REQUIRED gtkmm-4.0)
    include_directories(${GTKMM_INCLUDE_DIRS})
    list(APPEND LIBS ${GTKMM_LIBRARIES} -lgtkmm-4.0 -lglib-2.0)
endif()
